version: '3.3'
services:
  biketracker-nginx: 
    image: nginx:latest
    container_name: biketracker-nginx
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8054:80
  biketracker-keycloak:
    image: wizzn/keycloak:14
    container_name: biketracker-keycloak
    restart: unless-stopped    
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - PROXY_ADDRESS_FORWARDING=true  #important for reverse proxy    

  biketracker-frontend: 
    image: biketracker-frontend
    container_name: biketracker-frontend
    restart: unless-stopped